# Generated by Django 5.0.3 on 2024-04-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_persona_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='imagenes/default_image', upload_to='imagenes/'),
        ),
    ]
