# Generated by Django 5.0.3 on 2024-04-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_ticket_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
