# Generated by Django 5.0.3 on 2024-04-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_ticket_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='nombre',
        ),
    ]
