# Generated by Django 5.0.3 on 2024-04-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_persona_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoenfactura',
            old_name='factura',
            new_name='factura_id',
        ),
        migrations.RenameField(
            model_name='productoenticket',
            old_name='ticket',
            new_name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='numero',
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
