# Generated by Django 5.0.2 on 2024-04-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_facturas_numero_ticket_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('targeta', 'Tarjeta')], default='efectivo', max_length=20),
        ),
    ]
