# Generated by Django 5.0.2 on 2024-04-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_ticket_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Targeta', 'Tarjeta')], default='Efectivo', max_length=20),
        ),
    ]
