# Generated by Django 5.0.2 on 2024-04-27 14:33

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_ticket_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=9999999, validators=[myapp.models.validate_not_zero]),
        ),
    ]
