# Generated by Django 5.0.3 on 2024-05-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_persona_comp_banc'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Targeta', 'Tarjeta')], default='Efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='comp_banc',
            field=models.CharField(max_length=200),
        ),
    ]
