# Generated by Django 5.0.3 on 2024-05-26 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_facturas_metodo_pago_alter_persona_comp_banc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9999999)),
                ('data', models.DateTimeField()),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Targeta', 'Tarjeta')], default='Efectivo', max_length=20)),
                ('descripcio', models.CharField(max_length=300)),
                ('material_entregat', models.CharField(max_length=300)),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='ProducteReparacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
                ('reparacio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.reparacions')),
            ],
        ),
    ]
