# Generated by Django 5.0.3 on 2024-06-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_reparacions_productereparacio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='imagenes/gameOfThrones_small.jpg', upload_to='imagenes'),
        ),
    ]
