# Generated by Django 5.0.2 on 2024-07-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_persona_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='abono',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='abono',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
