# Generated by Django 5.0.2 on 2024-07-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_facturas_abono_ticket_abono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='abono',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='abono',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
