# Generated by Django 5.0.3 on 2024-07-07 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_ticket_abono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressupost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=9999999)),
            ],
        ),
        migrations.CreateModel(
            name='ProducteEnPressupost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.PositiveIntegerField(default=1)),
                ('Pressupost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.facturas')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
            ],
        ),
    ]
