# Generated by Django 5.0.3 on 2024-07-07 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_pressupost_producteenpressupost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producteenpressupost',
            name='Pressupost_id',
        ),
        migrations.AddField(
            model_name='producteenpressupost',
            name='pressupost_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.pressupost'),
        ),
    ]
