# Generated by Django 5.0.3 on 2024-07-07 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_remove_producteenpressupost_pressupost_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producteenpressupost',
            name='pressupost_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pressupost'),
        ),
    ]
