# Generated by Django 5.0.3 on 2024-07-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_producteenpressupost_pressupost_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producteenpressupost',
            old_name='pressupost_id',
            new_name='pressupost',
        ),
    ]
