# Generated by Django 5.0.3 on 2024-07-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_rename_pressupost_id_producteenpressupost_pressupost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoenfactura',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
