# Generated by Django 5.0.3 on 2024-07-08 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_productoenfactura_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.IntegerField(default='1')),
                ('nota', models.CharField(blank=True, max_length=100)),
                ('factura_compra', models.CharField(blank=True, max_length=50)),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
            ],
        ),
    ]
