# Generated by Django 5.0.3 on 2024-07-10 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_pedidos_rebut'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_factura', models.CharField(max_length=30)),
                ('data', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=9999999)),
            ],
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='factura_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.facturacompra'),
        ),
    ]
