# Generated by Django 5.0.3 on 2024-07-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_facturacompra_alter_pedidos_factura_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='factura_compra',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
