# Generated by Django 5.0.3 on 2024-07-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_pedidos_factura_compra_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='factura_compra_id',
        ),
    ]
