# Generated by Django 5.0.3 on 2024-07-10 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_remove_pedidos_factura_compra_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='factura_compra_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.facturacompra'),
            preserve_default=False,
        ),
    ]
