# Generated by Django 5.0.3 on 2024-07-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_alter_pedidos_factura_compra_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9999999),
        ),
    ]
