# Generated by Django 5.0.3 on 2024-07-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_alter_facturacompra_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='estat',
            field=models.CharField(default='pendent', max_length=50),
        ),
    ]
