# Generated by Django 5.0.3 on 2024-07-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_facturacompra_estat'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marge',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9999999),
        ),
        migrations.AddField(
            model_name='producto',
            name='preu_distribuidor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9999999),
        ),
        migrations.AddField(
            model_name='productoenfactura',
            name='marge',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9999999),
        ),
        migrations.AddField(
            model_name='productoenfactura',
            name='preu_distribuidor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9999999),
        ),
        migrations.AddField(
            model_name='productoenfactura',
            name='preu_venut',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9999999),
        ),
        migrations.AddField(
            model_name='productoenticket',
            name='marge',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9999999),
        ),
        migrations.AddField(
            model_name='productoenticket',
            name='preu_distribuidor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9999999),
        ),
        migrations.AddField(
            model_name='productoenticket',
            name='preu_venut',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9999999),
        ),
    ]
