# Generated by Django 5.0.3 on 2024-07-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_pressupost_facturat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressupost',
            name='facturat',
            field=models.IntegerField(blank=True),
        ),
    ]
