# Generated by Django 5.0.3 on 2024-07-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_alter_pressupost_facturat'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='procedencia',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='pressupost',
            name='facturat',
            field=models.CharField(default='no', max_length=100),
        ),
    ]
