# Generated by Django 5.0.3 on 2024-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_facturas_procedencia_alter_pressupost_facturat'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='taula_id_procedencia',
            field=models.IntegerField(default=0),
        ),
    ]
