# Generated by Django 5.0.3 on 2024-07-30 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_facturas_taula_id_procedencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('facturat', models.CharField(default='no', max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9999999)),
            ],
        ),
        migrations.CreateModel(
            name='ProducteEnReparacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.PositiveIntegerField(default=1)),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
                ('pressupost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.reparacio')),
            ],
        ),
    ]
