# Generated by Django 5.0.3 on 2024-07-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_reparacio_producteenreparacio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producteenreparacio',
            old_name='pressupost',
            new_name='reparacio',
        ),
    ]
