# Generated by Django 5.0.3 on 2024-08-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_avui'),
    ]

    operations = [
        migrations.AddField(
            model_name='avui',
            name='marge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9999999),
        ),
        migrations.AddField(
            model_name='avui',
            name='targeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9999999),
        ),
        migrations.AddField(
            model_name='avui',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9999999),
        ),
        migrations.AlterField(
            model_name='avui',
            name='calaix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9999999),
        ),
        migrations.AlterField(
            model_name='avui',
            name='ingressat_banc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9999999),
        ),
    ]
